### PR TITLE
Machine learning interpretation, Hierarchical Bayes how-to

### PR DESCRIPTION
**Pull request by drphilmarshall**
Hey @danielgruen @cpadavis I wrote up my notes on how to combine individual galaxy redshift posteriors hierarchically. This is all in Malz et al, but now here in our notation. I also added some more thoughts on stacking estimators, and how they relate to machine learning photo-z code outputs, and tried to homogenize the notation. This meant editing some of your equations, Daniel - would you mind checking through what I wrote to see if it makes sense, please? Thanks!

### CODE REVIEW

**Comment by danielgruen** [comment]
Hi Phil, I really like the additions and the approach to HBI in the last section! Some things that were not totally clear to me, maybe because I'm a HB newbie, below...
- in Definitions:  I'm not sure I consistently get what’s the relation between h and H and M and T. Is H a general model and h its parameters, T the true H with the true h, and M some assumed H with assumed h? Maybe list all these letters here and give an ostentative definition?
- eqn. 2: I guess this should be capital P_D and are you sure it is H and not T on the rhs?
- eqn. 5: Here we use H as the set of h and the model interchangeably, and A appears for the first time ... maybe just remove them from under the integral signs?
- end of section 5: I guess one important thing to mention for this re-prior-ization business is that we need to know the sampled t^k_i in addition to the z^k_i

**Comment by drphilmarshall** [comment]
Thanks Daniel! I addressed all your comments in the latest version. It's a bit clunky how I start talking about types as well as redshifts, but maybe its unavoidable? I'd still like it if we could do something (other than hierarchical inference) about the stacked estimator in the case where we have posteriors given M, not T - maybe you can see something to add, once you have merged this PR?

**Comment by danielgruen** [comment]
Thanks, looks good! I'll think about the type issue a bit more ... do you think we can just replace the (z_i, t_i) by the full a_i required to predict what the galaxy in question looks like? Depending on your Bayesian photo-z code, this might be a star formation history, amount of dust, metallicity etc., and certainly an absolute magnitude instead of just a discrete type.

**Comment by drphilmarshall** [comment]
Yeah, maybe - if we could bring my ramblings back into the common notation
that would be great! :-)

**Comment by danielgruen** [comment]
I've tried in the latest commit ... have a look!

2016-10-05 15:00 GMT-07:00 Phil Marshall notifications@github.com:

**Pull request merged**
